name       : python-mock
version    : 3.0.5
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/m/mock/mock-3.0.5.tar.gz : 83657d894c90d5681d62155c82bda9c1187827525880eda8ff5df4ec813437c3
license    : BSD-2-Clause
component  : programming.python
summary    : Rolling backport of unittest.mock for all Pythons
description: |
    mock is a library for testing in Python. It allows you to replace parts of your system under test with mock objects and make assertions about how they have been used.
builddeps  :
    - pkgconfig(python3)
    - pbr
    - python-funcsigs
    - python-six
rundeps    :
    - pbr
    - python-funcsigs
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
