name       : python-mock
version    : 2.0.0
release    : 4
source     :
    - https://pypi.python.org/packages/0c/53/014354fc93c591ccc4abff12c473ad565a2eb24dcd82490fae33dbf2539f/mock-2.0.0.tar.gz : b158b6df76edd239b8208d481dc46b6afd45a846b7812ff0ce58971cf5bc8bba
license    : BSD-2-Clause
component  : programming.python
summary    : Rolling backport of unittest.mock for all Pythons
description: |
    mock is a library for testing in Python. It allows you to replace parts of your system under test with mock objects and make assertions about how they have been used.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - pbr
    - python-funcsigs
    - python-six
rundeps    :
    - pbr
    - python-funcsigs
    - python-six
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
